FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY app_flutter /app/app_flutter

WORKDIR /app/app_flutter
RUN flutter pub get
RUN flutter config --enable-web
RUN flutter build web --release

FROM nginx:1.27-alpine
COPY infra/nginx/default.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/app_flutter/build/web /usr/share/nginx/html
